---
services:
  redis:
    image: redis:latest
    secrets:
      - gateway-redis-password
    command:
      [
        "sh",
        "-c",
        "redis-server --requirepass $$(cat /run/secrets/gateway-redis-password)",
      ]
    volumes:
      - redis:/data

volumes:
  redis:

secrets:
  gateway-redis-password:
    external: true

networks:
  default:
    driver: overlay
