---
services:
  database:
    image: postgres:latest
    secrets:
      - authentication-database-password
    networks:
      - default
    environment:
      POSTGRES_DB: kt_authentication
      POSTGRES_USER: kt_user
      POSTGRES_PASSWORD_FILE: /run/secrets/authentication-database-password
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:

secrets:
  authentication-database-password:
    external: true

networks:
  default:
    driver: overlay
