---
services:
  authentication-backend:
    # image: ghcr.io/kaiqkt/kt-authentication-api
    image: kaiqkt/kt-authentication-api:local
    configs:
      - source: spring_config
        target: /app/config/application.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/application.yml
    secrets:
      - authentication-database-password
      - access_token_secret
    networks:
      - authentication_dependencies_default
      - default
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
configs:
  spring_config:
    file: ./application.yml

secrets:
  authentication-database-password:
    external: true
  access_token_secret:
    external: true

networks:
  authentication_dependencies_default:
    external: true
  default:
    driver: overlay
