---
services:
  authentication-backend:
    image: kaiqkt/kt-authentication-api:latest
    configs:
      - source: spring_config
        target: /app/config/application.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/application.yml
      JAVA_TOOL_OPTIONS: -Xmx512m -XX:+UseContainerSupport # Remove
    secrets:
      - authentication_database_password
      - access_token_secret
    networks:
      - authentication_dependencies_default
      - default
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      resources:
        limits:
          memory: 2G # Remove

configs:
  spring_config:
    file: ./application.yml

secrets:
  authentication_database_password:
    external: true
  access_token_secret:
    external: true

networks:
  authentication_dependencies_default:
    external: true
  default:
    driver: overlay